### ISSUE TITLE
Catch pygit/libgit errors and convert to human-readable errors

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/salt-shaker#22]
Let's catch common pygit2 errors and raise a human readable error.

```
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/shaker/salt_shaker.py", line 193, in install_requirement
    repo = self._open_repo(repo_dir, formula['url'])
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/shaker/salt_shaker.py", line 317, in _open_repo
    credentials = pygit2.credentials.KeypairFromAgent(username)
```
means you don't have a new enough libgit2

```
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/shaker/salt_shaker.py", line 181, in install_requirements
    (repo_dir, _) = self.install_requirement(formula)
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/shaker/salt_shaker.py", line 193, in install_requirement
    repo = self._open_repo(repo_dir, formula['url'])
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/shaker/salt_shaker.py", line 322, in _open_repo
    credentials=credentials)
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/pygit2/__init__.py", line 265, in clone_repository
    check_error(err)
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/pygit2/errors.py", line 56, in check_error
    raise GitError(message)
_pygit2.GitError: Unsupported URL protocol
```
means you didn't compile it with libssh2

**Comment by ashb** [comment]
For the 'no libssh2' case we can check it with this snippet `pygit2.features & pygit2.GIT_FEATURE_SSH` instead of catching an error and having to parse the error string

**Comment by mattmb** [comment]
Top one there I didn't include the exception which is not helpful:
```
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/shaker/salt_shaker.py", line 193, in install_requirement
    repo = self._open_repo(repo_dir, formula['url'])
  File "/Users/stuart/.virtualenvs/tribunals_api_deploy/lib/python2.7/site-packages/shaker/salt_shaker.py", line 317, in _open_repo
    credentials = pygit2.credentials.KeypairFromAgent(username)
AttributeError: 'module' object has no attribute 'KeypairFromAgent'
```

**Comment by niallcreech** [comment]
SSH checking seems straightforward but with a non-aligned libgit2 version I'm not so sure. The specific exception isn't really the issue, as versions change so will the actual error. I can think of 2 ways to check, both pretty inelegant. ie.

(i) Have a 'check_libgit2()' function that contains a bunch of try/catch calls to check that they work before we start running proper

(ii) Just try/catch all pygit2 calls and make sure the logging gives some 'check your libgit2 version' as part of its message

**Comment by ashb** [comment]
So general 'versions don't match' errors we can't do much, but the specific case Matt mentioned we *can* test with a python check, so how about we:

- At import (or perhaps on first call?) we check that pygit and libgit2 has the features we need (`pygit2.features & pygit2.GIT_FEATURE_SSH` and `"module" in pygit2.credentials` right now)
- We then go with your second plan of catch all exceptions and include the message 'check libgit2 versions against pygit2 version' like you suggest.

**Comment by niallcreech** [comment]
Think its the most simple way. A generic pygit2 advice message on try/catch, this could be part of the one-off on-start checks, checking to see if the calls we will use work. But this would probably require setting them up for the check in the first place and could easily get ugly. Probably better to just try/catch them as we use them, its clearer if nothing else

**Comment by SteveMarshall** [comment]
Just hit this issue. Got this output with a version mismatch on pygit2:

```
Resolving formula dependencies: salt-shaker shake root_formula=ministryofjustice/sensu-formula
salt-shaker shake root_formula=ministryofjustice/sensu-formula
Traceback (most recent call last):
  File "/usr/local/bin/salt-shaker", line 4, in <module>
    from shaker.command_line import ShakerCommandLine
  File "/usr/local/lib/python2.7/site-packages/shaker/command_line.py", line 5, in <module>
    import salt_shaker
  File "/usr/local/lib/python2.7/site-packages/shaker/salt_shaker.py", line 12, in <module>
    import pygit2
  File "/usr/local/lib/python2.7/site-packages/pygit2/__init__.py", line 32, in <module>
    from _pygit2 import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/_pygit2.so, 2): Library not loaded: /usr/local/lib/libgit2.21.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/_pygit2.so
  Reason: image not found
Failed: (status = 1)
```
